# Setup
title: Letthem Blog
url: https://seleuchel.github.io
paginate: 1
baseurl: "/letthem_blog"
permalink: pretty
pagenate_path: "/letthem_blog/page:num/"
category_list: [ War, Forensic, Mal, APT, Privacy, ICS, Think, ZZZ, Basic, Issue, Web, Analy, CTI, Scenario , Info]

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Seleuchel
  url: https://seleuchel.github.io
  email: seleuchel@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog~
    url: /letthem_blog/archive

  - title: Category
    url: /letthem_blog/category

  - title: About
    url: /letthem_blog/about


